### ISSUE TITLE
Architecture: Big picture and data cleanup required for moving forward

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#569]
**WIP**

---

### Reference taxa by `taxon_id` instead of `name_id`
There are still a few cases of this.

Depends on:

- [x] "Replace and remove name and reference pickers" #440
- [x] "Associate type names by taxon_id instead of name_id" #446
  - [x] [not strictly required] post-migration cleanup [Open issue: Taxa with type names that cannot be resolved to a taxon](http://antcat.org/issues/11)
  - [x]  [not strictly required] post-migration cleanup [Open issue: Type names that had ambiguous type names](http://antcat.org/issues/17)
- [x] Fix broken `nam` tags (see http://antcat.org/issues/14)
- [x] `Persistent taxon ids when elevating/converting species/subspecies` #469

More data to cleanup:
- [x] [Taxt: Nam taxt tags](http://antcat.org/database_scripts/nam_taxt_tags)

Strictly not in need of cleanup, but illustrates the issue:
* [Catalog: Taxa with the same name cache value](http://antcat.org/database_scripts/taxa_with_the_same_name_cache_value)
* [Catalog: Taxa with the same name object](http://antcat.org/database_scripts/taxa_with_the_same_name_object)
* See also #182

---

### Relational Taxon-Reference linkage
Issue: #452 (for `ReferenceSection`s)

Data to cleanup:
- [ ] [Catalog: Non standard reference sections](http://antcat.org/database_scripts/non_standard_reference_sections)
- [x] Fix broken `tax` and `ref` tags (see http://antcat.org/issues/13 and http://antcat.org/issues/15)

---

### Deprecate synonyms table
Issue: #476

Depends on:

- [x] [Synonyms: Inconsistent synonyms](http://antcat.org/database_scripts/inconsistent_synonyms)
- [x] [Synonyms: Junior synonyms listed as another taxons senior](http://antcat.org/database_scripts/junior_synonyms_listed_as_another_taxons_senior)
- [x] [Synonyms: Taxa with both junior and senior synonyms](http://antcat.org/database_scripts/taxa_with_both_junior_and_senior_synonyms)
- [x] [Synonyms: Taxa with more than one senior synonym](http://antcat.org/database_scripts/taxa_with_more_than_one_senior_synonym)
- [x] [Synonyms: Species and subspecies with synonyms not in the same genus](http://antcat.org/database_scripts/species_and_subspecies_with_synonyms_not_in_the_same_genus)

**Comment by bpescador** [comment]
So it is clear I should start cleaning up the data: however, not clear from the above which needs to be done to move forward.  I will start at the top but let me know if I need to clean up all of the above.
