### ISSUE TITLE
Improve "Create combination" feature

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#570]
It started to fail a lot and not work at all after I added database constraints, but that's a good thing.

- [x] Feature for moving history (#464)
- [x] Create missing obsolete combination" button/page (#498)
- [x] Ability to select protonym when editing or creating new taxa (#585)
- [x] Help page listing records that may require updating. This will replace the "Create combination" feature. (#589)
