### ISSUE TITLE
Meta issue: Improve how we handle Name records

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#604]
### Remove existing nam tags
- [x] Inline broken nam links #605
- [x] Inline remaining nam links #605

### Delete orphaned records
- [x] *Optional*: Delete orphaned protonyms #430
- [ ] *Optional*: Delete orphaned names #717

### Cleanup name records
- [ ] *Maybe*: Split `FamilyOrSubfamilyName` into family and subfamily names #635
- [x] Nullify redundant `names.epithets` #667 (after #649)
- [ ] http://antcat.org/database_scripts/taxa_with_non_matching_name_types (fixed a bunch in #649 and #683)
- [x] http://antcat.org/database_scripts/higher_rank_names_containing_spaces #649
- [x] Dedup name records #662
- [x] Delete most 'unavailable misspelling's #653

### Dedupe names and prevent new cases
- [x] Change code to not reuse names in name pickers (#731)
  - [x] Delay creating names until inside taxa/protonyms controllers (#731)
  - [x] Dynamically generate `name_html` and `epithet_html` (part 1: #621, part 2: #631)
  - [x] Edit names in place and show where names are referenced #627
  - [ ] *Maybe*: Dynamically generate or at least validate `epithet` and `epithets` where possible. Requires some cleanup.
  - [x] Show name conflicts in taxon/protonym forms (name form: #665; taxon/protonym forms:  #731)
  - [x] Replace last name pickers (started in #440)
- [x] Change code to not reuse names elsewhere (ie outside of name pickers) #619
- [x] Dedup name records #662
  - [x] Fix names with type not matching taxon (except `FamilyOrSubfamilyName`s and `SubtribeName`s that we don't have to deal with now)
- [ ] *Maybe*: Add unique index.

### See also

* Support tricky names (mostly infrasubspecific names) #593

**Comment by jonkerz** [comment]
I consider this fixed for now. There's more work to be done, but let's create other issues for that.
