### ISSUE TITLE
Remove moved database columns

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#739]
- [x] ~`taxa.biogeograpic_region`, moved in #723~ #762
- [x] ~Type information, moved #689~ #762
  * `taxa.primary_type_information`
  * `taxa.secondary_type_information`
  * `taxa.type_notes`
- [x] ~Drop `synonyms`, deprecated in #740~ #745
