### ISSUE TITLE
[MAYBE] Inline `Name` records

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#767]
Meta-issue: #774

That is, move them to the `taxa` and `protonyms` tables. I think we want this.

* `Name`s as they are currently being used are more of "value objects" anyways
* Names belonging to taxa and protonyms have different rules for validation
* A `Taxon` or `Protonym` currently belongs to a `Name`, but it should be the other way around

TODO:

- [x] Deal with `FamilyOrSubfamilyName`s (#635)
- [x] Probably handle subtribes (#666)
- [x] Take care of http://antcat.org/database_scripts/taxa_with_non_matching_name_types
- [ ] Decide if it's better to do this before adding support for quadrinomials (#714)
- [x] Delete orphaned names (#717)
- [ ] Other things

**Comment by jonkerz** [comment]
Closing as... I don't know :)
